### ISSUE TITLE
Request for 128x128 OLED profile

### ISSUE THREAD

**Issue by dominicklee** [pauls-3d-things/u8g2-simulator#2]
Hi @uvwxy , congrats on this amazing project as well as all your other amazing projects! These are really nice and helpful for both hobbyists and developers!

I have a simple request. We have a project that uses a 128x128 OLED display and we have many users in our community who would like to use your simulator to design some UI for that. Would you mind adding a profile in your simulator for a 128x128 OLED display? That would be really helpful!

Thanks again  for your help! It means alot!

**Comment by dominicklee** [comment]
@uvwxy Would you please let me know if you could help us add that 128x128 profile? Thanks!

**Comment by uvwxy** [comment]
I deployed the version to https://p3dt.net/u8g2sim/

**Comment by dominicklee** [comment]
> I deployed the version to https://p3dt.net/u8g2sim/

Thank you so much, sir!  We appreciate your help!
