### ISSUE TITLE
Request for HTML based version

### ISSUE THREAD

**Issue by dominicklee** [pauls-3d-things/u8g2-simulator#3]
Hi @uvwxy sorry for the inconvenience. Is there a way we can run your web-based code on our LAMP server without installing NodeJS or npm? Would you mind sharing a version that is simply HTML and Javascript-based?

Thanks

**Comment by uvwxy** [comment]
https://p3dt.net/u8g2sim/

**Comment by uvwxy** [comment]
This is HTML and Javascript based. You don't need NodeJS to run this. Only for dependency management and building.
