### ISSUE TITLE
error when processing npm run start command，THX

### ISSUE THREAD

**Issue by scarrrr316** [pauls-3d-things/u8g2-simulator#4]
I have install node.js lite ,and run the npm run start command，it show error and there are the output below↓↓↓↓↓↓↓↓↓↓↓↓
`
D:\Downloads\u8g2-simulator-master>npm run start
> u8g2-sim@1.0.0 start D:\Downloads\u8g2-simulator-master
> npm-run-all clean init webpack:dev
> u8g2-sim@1.0.0 clean D:\Downloads\u8g2-simulator-master
> rimraf dist
> u8g2-sim@1.0.0 init D:\Downloads\u8g2-simulator-master
> npm-run-all init:**
> u8g2-sim@1.0.0 init:dist D:\Downloads\u8g2-simulator-master
> mkdirp dist
> u8g2-sim@1.0.0 init:css D:\Downloads\u8g2-simulator-master
> sass src/style.scss dist/bundle.css && cssmin dist/bundle.css > dist/bundle.min.css

> 'sass' 不是内部或外部命令，也不是可运行的程序或批处理文件。
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! u8g2-sim@1.0.0 init:css: `sass src/style.scss dist/bundle.css && cssmin dist/bundle.css > > dist/bundle.min.css`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the u8g2-sim@1.0.0 init:css script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\wong6\AppData\Roaming\npm-cache\_logs\2020-04-02T10_30_14_322Z-debug.log
> ERROR: "init:css" exited with 1.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! u8g2-sim@1.0.0 init: `npm-run-all init:**`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the u8g2-sim@1.0.0 init script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\wong6\AppData\Roaming\npm-cache\_logs\2020-04-02T10_30_14_457Z-debug.log
> ERROR: "init" exited with 1.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
>npm ERR! u8g2-sim@1.0.0 start: `npm-run-all clean init webpack:dev`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the u8g2-sim@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by uvwxy** [comment]
> 'sass'  不是内部或外部命令，也不是可运行的程序或批处理文件。
Translates to
> 'sass'  Not an internal or external command, nor a runnable program or batch file.

Please install sass https://sass-lang.com/install,

e.g. npm install -g sass

**Comment by scarrrr316** [comment]
i will try it later，thx！
