### ISSUE TITLE
Missing drawGlyph

### ISSUE THREAD

**Issue by imval** [pauls-3d-things/u8g2-simulator#5]
Hi,
It seems that the function drawGlyph is missing.
Would it be a lot of work to add it? 
It's super handy and can be used in conjunction with icon fonts like this one: https://github.com/olikraus/u8g2/wiki/fntgrpsiji

**Comment by uvwxy** [comment]
Hi @imval 

I added `drawGlyph` support, see https://p3dt.net/u8g2sim/  -> Code Examples -> Draw Glyph, then click on Loop Eval for a short demo.


Have fun :)
