### ISSUE TITLE
256x128 display

### ISSUE THREAD

**Issue by gionag** [pauls-3d-things/u8g2-simulator#8]
Hello !
thanks for such a nice idea, would help me (and others) a lot.

is it possible to have a 256x128 oled setup ?

thanks

**Comment by uvwxy** [comment]
<img width="1379" alt="Screenshot 2020-12-13 at 12 19 16" src="https://user-images.githubusercontent.com/930238/102010275-6d3dd400-3d3d-11eb-9489-86fa59606389.png">

Done.

**Comment by gionag** [comment]
.... thanks !
also a 256x64 would be awesome.

I promise this is the last request :)
