### ISSUE TITLE
256x64 setting

### ISSUE THREAD

**Issue by gionag** [pauls-3d-things/u8g2-simulator#9]
also a 256x64 setting would be awesome.

is it possible to have that ?

.... thanks !

**Comment by uvwxy** [comment]
I'll try to add a way to create generic screens on the fly, will take a while to this, so I'll add the single display first

**Comment by uvwxy** [comment]
<img width="1117" alt="Screenshot 2021-01-06 at 19 51 31" src="https://user-images.githubusercontent.com/930238/103808725-b6412980-5058-11eb-93dd-edf995a24944.png">

done.

**Comment by tinyboxxx** [comment]
Great work! Really helpful! Wish to have this simulator two years ago!

By the way, It will be better if we can customize the color of pixels, like a green or blue screen, rather than white.
